// Client-side initialization for Leaflet maps generated by the LeafletMaps transformer.
// This script is injected into every page via LeafletMaps.externalResources().
// It finds all .leaflet-map-container divs and initializes Leaflet maps from their data attributes.

type MarkerTypeDef = { type: string; color: string; iconName: string }

function createMarkerIcon(type: string, typesMap: Map<string, MarkerTypeDef>): L.DivIcon {
  const def = typesMap.get(type) ?? typesMap.get("default")
  const color = def?.color ?? "#3388ff"
  const iconName = def?.iconName ?? "map-marker-alt"

  let svg: string
  if (iconName === "map-marker") {
    // SpinOff → estrella de 5 puntas, centrada en (14,14) del viewBox 0 0 28 28
    svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 28 28" width="28" height="28"
      style="filter:drop-shadow(0 1px 2px rgba(0,0,0,0.5))">
      <polygon points="14,2 17.5,10.5 27,11.5 20,18 22,27 14,22.5 6,27 8,18 1,11.5 10.5,10.5"
        fill="${color}" stroke="rgba(255,255,255,0.6)" stroke-width="1"/>
    </svg>`
    return L.divIcon({
      html: svg,
      className: "",
      iconSize: [28, 28],
      iconAnchor: [14, 14],
      popupAnchor: [0, -16],
    })
  } else {
    // Default → pin gota con punto interior
    // path tip exactamente en (13, 38) = fondo del viewBox 0 0 26 38
    // CSS drop-shadow no afecta el bounding box del elemento (a diferencia del SVG filter)
    svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 26 38" width="26" height="38"
      style="filter:drop-shadow(0 2px 2px rgba(0,0,0,0.45))">
      <path d="M13 1C6.925 1 2 5.925 2 12c0 9 11 26 11 26S24 21 24 12C24 5.925 19.075 1 13 1z"
        fill="${color}" stroke="rgba(255,255,255,0.5)" stroke-width="1"/>
      <circle cx="13" cy="12" r="4.5" fill="white" opacity="0.85"/>
    </svg>`
    return L.divIcon({
      html: svg,
      className: "",
      iconSize: [26, 38],
      iconAnchor: [13, 38],
      popupAnchor: [0, -38],
    })
  }
}

function initLeafletMaps() {
  if (typeof L === "undefined") return

  document.querySelectorAll(".leaflet-map-container").forEach((el) => {
    const div = el as HTMLElement
    if (div.dataset.initialized) return
    div.dataset.initialized = "true"

    const imageUrl = div.dataset.image!
    const bounds: [[number, number], [number, number]] = JSON.parse(div.dataset.bounds!)
    const defaultZoom = parseFloat(div.dataset.defaultZoom!)
    const minZoom = parseFloat(div.dataset.minZoom!)
    const maxZoom = parseFloat(div.dataset.maxZoom!)
    const zoomDelta = parseFloat(div.dataset.zoomDelta!)
    const markers: Array<{
      loc: [number, number]
      link: string | null
      label: string | null
      type: string
    }> = JSON.parse(div.dataset.markers!)

    // Build marker type lookup from data-marker-types attribute
    const typesMap = new Map<string, MarkerTypeDef>()
    if (div.dataset.markerTypes) {
      const types: MarkerTypeDef[] = JSON.parse(div.dataset.markerTypes)
      types.forEach((t) => typesMap.set(t.type, t))
    }

    const map = L.map(div, {
      crs: L.CRS.Simple,
      minZoom,
      maxZoom,
      zoomDelta,
      zoomSnap: zoomDelta,
      attributionControl: false,
      scrollWheelZoom: true,
    })

    const imageBounds: [[number, number], [number, number]] = [[0, 0], [bounds[1][0], bounds[1][1]]]
    L.imageOverlay(imageUrl, imageBounds).addTo(map)
    map.fitBounds(imageBounds)
    map.setZoom(defaultZoom)

    markers.forEach(({ loc, link, label, type }) => {
      const icon = createMarkerIcon(type ?? "default", typesMap)
      const marker = L.marker([loc[0], loc[1]], { icon }).addTo(map)

      // Show label as hover tooltip when available
      if (label) {
        marker.bindTooltip(label, { direction: "top", offset: [0, -28] })
      }

      if (link) {
        // Direct navigation on click (same behaviour as Obsidian plugin)
        marker.on("click", () => { window.location.href = link })
        marker.on("add", () => {
          marker.getElement()?.style.setProperty("cursor", "pointer")
        })
      } else if (label && !marker.getTooltip()) {
        // No link — just show label in a popup
        marker.bindPopup(label)
      }
    })
  })
}

// Run on initial load and after Quartz SPA navigation
document.addEventListener("DOMContentLoaded", initLeafletMaps)
document.addEventListener("nav", initLeafletMaps)
